---
# copyright Utrecht University

- name: Ensure snapd is installed
  package:
    name: snapd
    state: present
  register: snapd_installed


- name: Ensure snapd is enabled
  systemd:
    name: snapd.socket
    enabled: true


- name: Enable snap classic support
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link


- name: Update snap after install
  become: yes
  shell: systemctl start snapd; snap install core; snap refresh core
  changed_when: true
  failed_when: false
  when: snapd_installed is changed
